### ISSUE TITLE
iScroll 4 horizontal scroll issue on iOS 7

### ISSUE THREAD

**Issue by mandoz** [cubiq/iscroll#503]
Hello,

We have a mobile application that uses iScroll 4 and its working great on iOS 6.

When we were testing the application on iOS7 we found a strange behavior.

All vertical scrolls are working perfectly on iOS7, however we have a few pages where we have a few horizontal scrolls within the main vertical page scroll.
The horizontal scrolls simply stopped working, and upon inspecting the elements we can see that instead of having the elements line up in a row beyond the edges of the screen, they are actually stacked up under each other in rows and are hidden because of the overflow:hidden CSS property.

Upon further inspection on iOS6 and iOS7 we saw that the UL element that should be horizontally scrolled has the width of for example 2000+ px, while on iOS7 it remains under 320px.

Below is our HTML:

``` html
<div class="horizontalScroller" id="scroller1">
     <ul>
          <li>
               <div class="channel-anchor" data-href="###">
                    <div class="channel-holder">
                         <img src="imagesrc"/>
                    </div>
               </div>
          </li>
...
     </ul>
</div>
```

CSS

``` css
.horizontalScroller ul{
     height: 120px;
     width: auto;
     margin-left:10px;
     margin-top:5px;
     white-space:nowrap;
}


.horizontalScroller li{    
     height: 100%;
     display:inline-block; 
}

.channel-anchor {
    background: url(images/channels/channel-holder.png) no-repeat;      
    height: 100px;
    width: 106px;
    text-align: center;
    margin-left:5px;
    display: table;
    position: relative;
    float: right;
}

.channel-holder  {
    top: 50%;
    width: 50px;
    display: table-cell;
    vertical-align: middle;
}


.channel-holder img {
    width: 50px;
    height: auto;
    margin-left: auto;
    margin-right: auto;
    top: -50%;
    display: block;

}
```

JS

``` js
var myScroll;
myScroll = new iScroll('scroller1', {
    hScroll : true,
    vScroll : false,
    hScrollbar : false,
    zoom : false
});

myScroll.refresh;
```

I am assuming it has something to do with the HTML/CSS implementation in the new mobile safari, and how that affects width calculation of content.
