### ISSUE TITLE
Miscalculating heights in iOS WebKit on phone

### ISSUE THREAD

**Issue by mikehdt** [cubiq/iscroll#856]
I have an issue specific to the iOS variants of WebKit. On my page is a fixed-position block, roughly the height of the page, with an overflow iscroll list in it. Without scrolling the page behind, on first load, the height is correctly calculated.

As soon as you scroll the page behind, the Safari toolbars shrink away and iscroll adds too much height to the container, leaving a gap at the bottom. If you then scroll the page back up so that the address bar and toolbar reappear, iscroll doesn't add enough height to the container and so the last item(s) get cropped off.

I would add a CodePen example, but in testing because of the way that they inject a toolbar when viewing (even in fullscreen) a CodePen demo for this can't work correctly on an actual device as fixed positioning breaks.

A rough sketch of the problem code would be:
```css
.sidebar {
  position: fixed;
  width: 26rem;
  top:    2rem;
  bottom: 2rem;
  left:   2rem;
  background-color: #eee;
}
.scrollable-content {
	position: relative;
	height: 100%;
	overflow: hidden;
}
```

```html
<div class="sidebar">
	<div class="scrollable-content">
		<ul>
			<li>&nbsp;</li>
			[insert enough content here to be scrollable with iscroll]
		</ul>
	</div>
</div>

[insert enough content here to allow the page behind to be independently scrollable]
```

```javascript
var scroller = new IScroll('.scrollable-content');
```

I'll continue to test around this, but it seems very difficult as the calculations are correct on page initialisation. Then, the same values are reused when the toolbars shrink (hence the extra space) and then the values are calculated too small when toolbars are made to reappear.

I've also tried hooking in to calling the .resize() method on page scroll without success.

Thoughts appreciated.
